[theme]
base = "dark"  # or "light"
primaryColor = "#ff4b4b"  # Red accent
backgroundColor = "#0e1117"  # Dark background
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
